INSERT INTO ACCOUNT (ACCOUNT_ID,ACCOUNT_HOLDER_ID,STATUS,CURRENCY,ACCOUNT_TYPE,ACCOUNT_SUBTYPE,NICKNAME,ACCOUNT_SCHEME_NAME,ACCOUNT_IDENTIFICATION,ACCOUNT_NAME,ACCOUNT_SECONDARY_IDENTIFICATION,BALANCE_CREDIT_DEBIT_INDICATOR,BALANCE_TYPE,BALANCE_AMOUNT,BALANCE_CURRENCY)
VALUES
('22289','11111','Enabled','GBP','PERSONAL','CurrentAccount','Bills','UK.OBIE.SortCodeAccountNumber','80200110203345','Mr Kevin','00021','Credit','InterimAvailable','30000.00','GBP');

INSERT INTO ACCOUNT (ACCOUNT_ID,ACCOUNT_HOLDER_ID,STATUS,CURRENCY,ACCOUNT_TYPE,ACCOUNT_SUBTYPE,NICKNAME,ACCOUNT_SCHEME_NAME,ACCOUNT_IDENTIFICATION,ACCOUNT_NAME,ACCOUNT_SECONDARY_IDENTIFICATION,BALANCE_CREDIT_DEBIT_INDICATOR,BALANCE_TYPE,BALANCE_AMOUNT,BALANCE_CURRENCY)
VALUES
('31820','22222','Enabled','GBP','PERSONAL','CurrentAccount','Household','UK.OBIE.SortCodeAccountNumber','80200110203348','ACME Inc','0002','Credit','InterimAvailable','70000.00','GBP');

COMMIT;