INSERT INTO ACCOUNT (ACCOUNT_ID,ACCOUNT_HOLDER_ID,STATUS,CURRENCY,ACCOUNT_TYPE,ACCOUNT_SUBTYPE,NICKNAME,ACCOUNT_SCHEME_NAME,ACCOUNT_IDENTIFICATION,ACCOUNT_NAME,ACCOUNT_SECONDARY_IDENTIFICATION,BALANCE_CREDIT_DEBIT_INDICATOR,BALANCE_TYPE,BALANCE_AMOUNT,BALANCE_CURRENCY)
VALUES
('22290','11111','Enabled','GBP','PERSONAL','CurrentAccount','Rainy Day','UK.OBIE.SortCodeAccountNumber','80200110203345','Kevin','00021','Credit','InterimAvailable','28000.00','GBP');

INSERT INTO ACCOUNT (ACCOUNT_ID,ACCOUNT_HOLDER_ID,STATUS,CURRENCY,ACCOUNT_TYPE,ACCOUNT_SUBTYPE,NICKNAME,ACCOUNT_SCHEME_NAME,ACCOUNT_IDENTIFICATION,ACCOUNT_NAME,ACCOUNT_SECONDARY_IDENTIFICATION,BALANCE_CREDIT_DEBIT_INDICATOR,BALANCE_TYPE,BALANCE_AMOUNT,BALANCE_CURRENCY)
VALUES
('22291','11111','Enabled','GBP','PERSONAL','CurrentAccount','Household','UK.OBIE.SortCodeAccountNumber','80200110203348','Kevin','0002','Credit','InterimAvailable','70000.00','GBP');

INSERT INTO ACCOUNT (ACCOUNT_ID,ACCOUNT_HOLDER_ID,STATUS,CURRENCY,ACCOUNT_TYPE,ACCOUNT_SUBTYPE,NICKNAME,ACCOUNT_SCHEME_NAME,ACCOUNT_IDENTIFICATION,ACCOUNT_NAME,ACCOUNT_SECONDARY_IDENTIFICATION,BALANCE_CREDIT_DEBIT_INDICATOR,BALANCE_TYPE,BALANCE_AMOUNT,BALANCE_CURRENCY)
VALUES
('22292','11111','Enabled','GBP','PERSONAL','CurrentAccount','Monthly Bills','UK.OBIE.SortCodeAccountNumber','80200110203320','Kevin','00021','Credit','InterimAvailable','28000.00','GBP');

INSERT INTO ACCOUNT (ACCOUNT_ID,ACCOUNT_HOLDER_ID,STATUS,CURRENCY,ACCOUNT_TYPE,ACCOUNT_SUBTYPE,NICKNAME,ACCOUNT_SCHEME_NAME,ACCOUNT_IDENTIFICATION,ACCOUNT_NAME,ACCOUNT_SECONDARY_IDENTIFICATION,BALANCE_CREDIT_DEBIT_INDICATOR,BALANCE_TYPE,BALANCE_AMOUNT,BALANCE_CURRENCY)
VALUES
('22293','22222','Enabled','GBP','PERSONAL','CurrentAccount','Household','UK.OBIE.SortCodeAccountNumber','80200110203321','Fred','0002','Credit','InterimAvailable','70000.00','GBP');

INSERT INTO ACCOUNT (ACCOUNT_ID,ACCOUNT_HOLDER_ID,STATUS,CURRENCY,ACCOUNT_TYPE,ACCOUNT_SUBTYPE,NICKNAME,ACCOUNT_SCHEME_NAME,ACCOUNT_IDENTIFICATION,ACCOUNT_NAME,ACCOUNT_SECONDARY_IDENTIFICATION,BALANCE_CREDIT_DEBIT_INDICATOR,BALANCE_TYPE,BALANCE_AMOUNT,BALANCE_CURRENCY)
VALUES
('22294','22222','Enabled','GBP','PERSONAL','CurrentAccount','Rainy Day','UK.OBIE.SortCodeAccountNumber','80200110203322','Kevin','00021','Credit','InterimAvailable','28000.00','GBP');

INSERT INTO ACCOUNT (ACCOUNT_ID,ACCOUNT_HOLDER_ID,STATUS,CURRENCY,ACCOUNT_TYPE,ACCOUNT_SUBTYPE,NICKNAME,ACCOUNT_SCHEME_NAME,ACCOUNT_IDENTIFICATION,ACCOUNT_NAME,ACCOUNT_SECONDARY_IDENTIFICATION,BALANCE_CREDIT_DEBIT_INDICATOR,BALANCE_TYPE,BALANCE_AMOUNT,BALANCE_CURRENCY)
VALUES
('22295','55555','Enabled','GBP','PERSONAL','CurrentAccount','Household','UK.OBIE.SortCodeAccountNumber','80200110203323','Jane','0002','Credit','InterimAvailable','70000.00','GBP');

INSERT INTO ACCOUNT (ACCOUNT_ID,ACCOUNT_HOLDER_ID,STATUS,CURRENCY,ACCOUNT_TYPE,ACCOUNT_SUBTYPE,NICKNAME,ACCOUNT_SCHEME_NAME,ACCOUNT_IDENTIFICATION,ACCOUNT_NAME,ACCOUNT_SECONDARY_IDENTIFICATION,BALANCE_CREDIT_DEBIT_INDICATOR,BALANCE_TYPE,BALANCE_AMOUNT,BALANCE_CURRENCY)
VALUES
('22296','55555','Enabled','GBP','PERSONAL','CurrentAccount','Monthly Bills','UK.OBIE.SortCodeAccountNumber','80200110203324','Jane','00021','Credit','InterimAvailable','28000.00','GBP');

INSERT INTO ACCOUNT (ACCOUNT_ID,ACCOUNT_HOLDER_ID,STATUS,CURRENCY,ACCOUNT_TYPE,ACCOUNT_SUBTYPE,NICKNAME,ACCOUNT_SCHEME_NAME,ACCOUNT_IDENTIFICATION,ACCOUNT_NAME,ACCOUNT_SECONDARY_IDENTIFICATION,BALANCE_CREDIT_DEBIT_INDICATOR,BALANCE_TYPE,BALANCE_AMOUNT,BALANCE_CURRENCY)
VALUES
('22297','66666','Enabled','GBP','CORPORATE','CurrentAccount','Receipts','UK.OBIE.SortCodeAccountNumber','80200110203325','Dillards','0002','Credit','InterimAvailable','70000.00','GBP');

INSERT INTO ACCOUNT (ACCOUNT_ID,ACCOUNT_HOLDER_ID,STATUS,CURRENCY,ACCOUNT_TYPE,ACCOUNT_SUBTYPE,NICKNAME,ACCOUNT_SCHEME_NAME,ACCOUNT_IDENTIFICATION,ACCOUNT_NAME,ACCOUNT_SECONDARY_IDENTIFICATION,BALANCE_CREDIT_DEBIT_INDICATOR,BALANCE_TYPE,BALANCE_AMOUNT,BALANCE_CURRENCY)
VALUES
('22298','77777','Enabled','GBP','CORPORATE','CurrentAccount','Receipts','UK.OBIE.SortCodeAccountNumber','80200110203326','Travel Visa','0002','Credit','InterimAvailable','75600.00','GBP');

INSERT INTO ACCOUNT (ACCOUNT_ID,ACCOUNT_HOLDER_ID,STATUS,CURRENCY,ACCOUNT_TYPE,ACCOUNT_SUBTYPE,NICKNAME,ACCOUNT_SCHEME_NAME,ACCOUNT_IDENTIFICATION,ACCOUNT_NAME,ACCOUNT_SECONDARY_IDENTIFICATION,BALANCE_CREDIT_DEBIT_INDICATOR,BALANCE_TYPE,BALANCE_AMOUNT,BALANCE_CURRENCY)
VALUES
('22299','88888','Enabled','GBP','CORPORATE','CurrentAccount','Receipts','UK.OBIE.SortCodeAccountNumber','80200110203327','OUC Utilities','0002','Credit','InterimAvailable','12500.00','GBP');

COMMIT;
