INSERT INTO VALIDATION_COMPLETE(DOMESTIC_PAYMENT_ID, CREATION_DATE_TIME, ENTRYCOUNT) VALUES ("23468326", NOW(), 1);
INSERT INTO VALIDATION_COMPLETE(DOMESTIC_PAYMENT_ID, CREATION_DATE_TIME, ENTRYCOUNT) VALUES ("23468326", NOW(), 1);
INSERT INTO VALIDATION_COMPLETE(DOMESTIC_PAYMENT_ID, CREATION_DATE_TIME, ENTRYCOUNT) VALUES ("23468326", NOW(), 1);
INSERT INTO VALIDATION_COMPLETE(DOMESTIC_PAYMENT_ID, CREATION_DATE_TIME, ENTRYCOUNT) VALUES ("23468326", NOW(), 1);
INSERT INTO VALIDATION_COMPLETE(DOMESTIC_PAYMENT_ID, CREATION_DATE_TIME, ENTRYCOUNT) VALUES ("23468326", NOW(), 1);


INSERT INTO AML_CHECK_COMPLETE(DOMESTIC_PAYMENT_ID, CREATION_DATE_TIME, ENTRYCOUNT) VALUES ("23468326", NOW(), 1);
INSERT INTO AML_CHECK_COMPLETE(DOMESTIC_PAYMENT_ID, CREATION_DATE_TIME, ENTRYCOUNT) VALUES ("23468326", NOW(), 1);
INSERT INTO AML_CHECK_COMPLETE(DOMESTIC_PAYMENT_ID, CREATION_DATE_TIME, ENTRYCOUNT) VALUES ("23468326", NOW(), 1);
INSERT INTO AML_CHECK_COMPLETE(DOMESTIC_PAYMENT_ID, CREATION_DATE_TIME, ENTRYCOUNT) VALUES ("23468326", NOW(), 1);
INSERT INTO AML_CHECK_COMPLETE(DOMESTIC_PAYMENT_ID, CREATION_DATE_TIME, ENTRYCOUNT) VALUES ("23468326", NOW(), 1);

INSERT INTO FRAUD_CHECK_COMPLETE(DOMESTIC_PAYMENT_ID, CREATION_DATE_TIME, ENTRYCOUNT) VALUES ("23468326", NOW(), 1);
INSERT INTO FRAUD_CHECK_COMPLETE(DOMESTIC_PAYMENT_ID, CREATION_DATE_TIME, ENTRYCOUNT) VALUES ("23468326", NOW(), 1);
INSERT INTO FRAUD_CHECK_COMPLETE(DOMESTIC_PAYMENT_ID, CREATION_DATE_TIME, ENTRYCOUNT) VALUES ("23468326", NOW(), 1);
INSERT INTO FRAUD_CHECK_COMPLETE(DOMESTIC_PAYMENT_ID, CREATION_DATE_TIME, ENTRYCOUNT) VALUES ("23468326", NOW(), 1);
INSERT INTO FRAUD_CHECK_COMPLETE(DOMESTIC_PAYMENT_ID, CREATION_DATE_TIME, ENTRYCOUNT) VALUES ("23468326", NOW(), 1);

INSERT INTO AUDIT_COMPLETE(DOMESTIC_PAYMENT_ID, CREATION_DATE_TIME, ENTRYCOUNT) VALUES ("23468326", NOW(), 1);
INSERT INTO AUDIT_COMPLETE(DOMESTIC_PAYMENT_ID, CREATION_DATE_TIME, ENTRYCOUNT) VALUES ("23468326", NOW(), 1);
INSERT INTO AUDIT_COMPLETE(DOMESTIC_PAYMENT_ID, CREATION_DATE_TIME, ENTRYCOUNT) VALUES ("23468326", NOW(), 1);
INSERT INTO AUDIT_COMPLETE(DOMESTIC_PAYMENT_ID, CREATION_DATE_TIME, ENTRYCOUNT) VALUES ("23468326", NOW(), 1);
INSERT INTO AUDIT_COMPLETE(DOMESTIC_PAYMENT_ID, CREATION_DATE_TIME, ENTRYCOUNT) VALUES ("23468326", NOW(), 1);

INSERT INTO PAYMENT_NETWORK_SENT(DOMESTIC_PAYMENT_ID, CREATION_DATE_TIME, ENTRYCOUNT) VALUES ("23468326", NOW(), 1);
INSERT INTO PAYMENT_NETWORK_SENT(DOMESTIC_PAYMENT_ID, CREATION_DATE_TIME, ENTRYCOUNT) VALUES ("23468326", NOW(), 1);
INSERT INTO PAYMENT_NETWORK_SENT(DOMESTIC_PAYMENT_ID, CREATION_DATE_TIME, ENTRYCOUNT) VALUES ("23468326", NOW(), 1);
INSERT INTO PAYMENT_NETWORK_SENT(DOMESTIC_PAYMENT_ID, CREATION_DATE_TIME, ENTRYCOUNT) VALUES ("23468326", NOW(), 1);
INSERT INTO PAYMENT_NETWORK_SENT(DOMESTIC_PAYMENT_ID, CREATION_DATE_TIME, ENTRYCOUNT) VALUES ("23468326", NOW(), 1);

INSERT INTO PAYMENT_NETWORK_CONFIRMED(DOMESTIC_PAYMENT_ID, CREATION_DATE_TIME, ENTRYCOUNT) VALUES ("23468326", NOW(), 1);
INSERT INTO PAYMENT_NETWORK_CONFIRMED(DOMESTIC_PAYMENT_ID, CREATION_DATE_TIME, ENTRYCOUNT) VALUES ("23468326", NOW(), 1);
INSERT INTO PAYMENT_NETWORK_CONFIRMED(DOMESTIC_PAYMENT_ID, CREATION_DATE_TIME, ENTRYCOUNT) VALUES ("23468326", NOW(), 1);
INSERT INTO PAYMENT_NETWORK_CONFIRMED(DOMESTIC_PAYMENT_ID, CREATION_DATE_TIME, ENTRYCOUNT) VALUES ("23468326", NOW(), 1);
INSERT INTO PAYMENT_NETWORK_CONFIRMED(DOMESTIC_PAYMENT_ID, CREATION_DATE_TIME, ENTRYCOUNT) VALUES ("23468326", NOW(), 1);

COMMIT;
