create table AML_CHECK_COMPLETE(ID BIGINT NOT NULL AUTO_INCREMENT, 
DOMESTIC_PAYMENT_ID VARCHAR(256) NULL, 
CREATION_DATE_TIME TIMESTAMP NULL,
ENTRYCOUNT INT,
REMITTANCE_INFORMATION_UNSTRUCTURED VARCHAR(256) NULL, PRIMARY KEY (ID));

create table AUDIT_COMPLETE(ID BIGINT NOT NULL AUTO_INCREMENT, 
DOMESTIC_PAYMENT_ID VARCHAR(256) NULL, 
CREATION_DATE_TIME TIMESTAMP NULL,
ENTRYCOUNT INT,
REMITTANCE_INFORMATION_UNSTRUCTURED VARCHAR(256) NULL, PRIMARY KEY (ID));

create table CORE_BANKING_COMPLETE(ID BIGINT NOT NULL AUTO_INCREMENT, 
DOMESTIC_PAYMENT_ID VARCHAR(256) NULL, 
CREATION_DATE_TIME TIMESTAMP NULL,
ENTRYCOUNT INT,
REMITTANCE_INFORMATION_UNSTRUCTURED VARCHAR(256) NULL, PRIMARY KEY (ID));

create table FRAUD_CHECK_COMPLETE(ID BIGINT NOT NULL AUTO_INCREMENT, 
DOMESTIC_PAYMENT_ID VARCHAR(256) NULL, 
CREATION_DATE_TIME TIMESTAMP NULL,
ENTRYCOUNT INT,
REMITTANCE_INFORMATION_UNSTRUCTURED VARCHAR(256) NULL, PRIMARY KEY (ID));

create table PAYMENT_NETWORK_CONFIRMED(ID BIGINT NOT NULL AUTO_INCREMENT, 
DOMESTIC_PAYMENT_ID VARCHAR(256) NULL, 
CREATION_DATE_TIME TIMESTAMP NULL,
ENTRYCOUNT INT,
REMITTANCE_INFORMATION_UNSTRUCTURED VARCHAR(256) NULL, PRIMARY KEY (ID));

create table PAYMENT_NETWORK_SENT(ID BIGINT NOT NULL AUTO_INCREMENT, 
DOMESTIC_PAYMENT_ID VARCHAR(256) NULL, 
CREATION_DATE_TIME TIMESTAMP NULL,
ENTRYCOUNT INT,
REMITTANCE_INFORMATION_UNSTRUCTURED VARCHAR(256) NULL, PRIMARY KEY (ID));

create table VALIDATION_COMPLETE(ID BIGINT NOT NULL AUTO_INCREMENT, 
DOMESTIC_PAYMENT_ID VARCHAR(256) NULL, 
CREATION_DATE_TIME TIMESTAMP NULL,
ENTRYCOUNT INT,
REMITTANCE_INFORMATION_UNSTRUCTURED VARCHAR(256) NULL, PRIMARY KEY (ID));

COMMIT;
