create table VALIDATION_COMPLETE(ID BIGINT NOT NULL AUTO_INCREMENT, 
DOMESTIC_PAYMENT_ID VARCHAR(256) NULL, 
CREATION_DATE_TIME TIMESTAMP NULL,
REMITTANCE_INFORMATION_UNSTRUCTURED VARCHAR(256) NULL, PRIMARY KEY (ID)); 
